version: 1
disable_existing_loggers: False
handlers:
  default:
    class: rich.logging.RichHandler
    level: DEBUG
    rich_tracebacks: true
    show_level: true
    markup: true
    show_path: true
  access:
    class: rich.logging.RichHandler
    level: DEBUG
    rich_tracebacks: true
    show_level: false
    markup: true
    show_path: false
loggers:
  uvicorn.error:
    level: DEBUG
    handlers:
      - default
    propagate: no
  uvicorn.access:
    level: DEBUG
    handlers:
      - access
    propagate: no
root:
    level: DEBUG
    handlers: [default]