[project]
name = "llm-rag-demo"
version = "0.1.0"
description = "LLM RAG Demo Project"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.131.0",
]
[dependency-groups]
dev = [
    "ipython>=9.7.0",
    "pre-commit>=4.2.0",
    "pyrefly>=0.41.3",
    "ruff>=0.11.12",
]